config/routes.rb
Rails.application.routes.draw do
  resources :trades
  resources :conversations do
    resources :messages
  end
  root to: 'trades#index'
  # root to: 'static_pages#index'
  
  get   'about', to: 'static_pages#about'
  get   'contact', to: 'static_pages#contact'
  get   'privacy', to: 'static_pages#privacy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/trade.rb
# == Schema Information
#
# Table name: trades
#
#  id          :integer          not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_trades_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Trade < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all.includes([:user, images_attachments: :blob])
  end

  # GET /trades/1
  # GET /trades/1.json
  def show

  end

  # GET /trades/new
  def new
    @trade = current_user.trades.build
  end

  # GET /trades/1/edit
  def edit
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = current_user.trades.build(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1
  # PATCH/PUT /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url, notice: 'Trade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.includes([images_attachments: :blob]).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:title, :description, :user_id, images: [])
    end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_form.html.erb
<%= simple_form_for(@trade) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <% if @trade.errors.any? %>
      <div class="errors">
        <p><%= @trade.errors.count %> Prevented this trade from saving</p>
        <ul>
          <% @trade.errors.full_messages.each do |msg| %>
            <li><%= msg  %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

   <div class="field">
      <div class="control">
        <%= f.input :title, required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :description, required: true, autofocus: true, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :images, as: :file,  input_html: { multiple: true, direct_upload: true }, label: false, wrapper: false %>
      </div>
    </div>


  <%= f.button :submit, class: 'button is-dark mt3' %>
<% end %>

app/views/trades/_trade.html.erb
<div class="card">
  <div class="card-image">
    <figure class="image is-square">
      <%= link_to image_tag(trade.images.first), trade if trade.images.attached?%>
    </figure>
  </div>
  <div class="card-content">
    <h3 class="pt1 title is-5"><%= trade.title %></h3>
    <p class="pv1"><%= truncate(trade.description, length: 120) %></p>
    <div class="media pt3">
      <div class="media-left pt3">
        <figure class="image is-48x48">
          <%= gravatar_for(trade.user, size: 96) %>
        </figure>
      </div>
      <div class="media-content">
        <p class="has-text-weight-bold mb0"><%= trade.user.first_name %></p>
        <p class="is-italic mb0"><time>posted <%= time_ago_in_words(trade.created_at) %> ago</time></p>
      </div>
    </div>
  </div>
</div>

app/views/trades/edit.html.erb
<h1 class="title is-3">Editing Trade</h1>

<%= render 'form', trade: @trade %>

app/views/trades/index.html.erb
<h1 class="title is-1">Trades</h1>
<p class="subtitle is-5">Looking to get rid of gear but not lose money. Trade some of your gear!</p>
<div class="columns">
<% @trades.each do |trade| %>
  <div class="column is-3">
    <%= render trade, trade: trade %>
  </div>
<% end %>
</div>

app/views/trades/new.html.erb
<h1 class="title is-3">New Trade</h1>

<%= render 'form', trade: @trade %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<div class="columns">
  <div class="column is-8">
    <h1 class="title is-1"><%= @trade.title %></h1>
    <div class="content">
      <p class="pb3 border-bottom">Post <%= time_ago_in_words(@trade.created_at) %> ago</p>
      <div class="pt1"><%= sanitize markdown_to_html(@trade.description) %></div>
    </div>

    <% if @trade.images.attached? %>
      <div class="columns is-multiline">
        <% @trade.images.each do |image| %>
          <div class="column is-one-third">
            <%= image_tag image %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="column is-3 is-offset-1">
    <% if trade_author(@trade) %>
      <div class="bg-light pa3 mb4 border-radius-3">
        <p class="f6 pb1">Author actions:</p>
        <div class="button-group">
          <%= link_to "Edit trade: #{@trade.title}", edit_trade_path(@trade), class: 'button is-small' %>
          <%= link_to "Back", trades_path, class: "button is-small" %>
        </div>
      </div>
    <% end %>
    <div class="pr5 mb4">
      <p class="text-align-left f6">Trade author:</p>
      <div class="inline-block nudge-down-10"><%= gravatar_for @trade.user, size: 32 %></div>
      <div class="inline-block"><%= @trade.user.first_name %></div>
    </div>
    <% if user_signed_in? && current_user.id != @trade.user_id %>
      <%= link_to "Message #{@trade.user.first_name}", conversations_path(sender_id: current_user.id, recipient_id: @trade.user.id), method: 'post', class:"button is-link" %>
    <% elsif user_signed_in? && current_user.id == @trade.user_id  %>
      <%= link_to "Conversations", conversations_path %>
    <% else %>

    <%= link_to "Sign up to message #{@trade.user.first_name}", new_user_registration_path %>
    <% end %>
  </div>
</div>